spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: data
      username: user
      password: mydata
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    password: Pass*4
    jedis:
      pool:
        max-idle: 50
        max-wait: 5000
props:
  driver:
    path: /usr/local/chromedriver
  proxypool:
    site: http://101.37.89.200
    port: 5000